AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'app/jobs/generate_answer_job.rb'  # Exclude until we can refactor
    - 'app/controllers/concerns/salesforce_gpt_concern.rb'
    - 'app/controllers/concerns/gpt_concern.rb'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 50 # sets maximum block length to 25 lines
  AllowedMethods: ['describe', 'context']
  Exclude:
    - 'spec/**/*.rb' # Excludes all spec files from this cop

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 40  

Layout/LineLength:
  Max: 200

Lint/MissingSuper:
  Exclude:
    - 'app/policies/*.rb'
