development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: fack_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: fack_production
  ssl_params: { verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %> }

# https://edgeguides.rubyonrails.org/action_cable_overview.html#redis-adapter
# https://help.heroku.com/HC0F8CUS/redis-connection-issues